Adding missing require
When I ran `$ rake spec:coverage:models` I encountered:

```console
./app/models/sipity/models/work_area.rb:15:in `<class:WorkArea>':
  undefined method `configure_as_a_processible_entity' for
  Sipity::Models::Processing:Module (NoMethodError)
```

This fixes that problem.